@startuml

Goal <-- SimpleGoal
Goal <-- EternalGoal
Goal <-- ChecklistGoal


+class UserInterface
{
-_goalList: List<Goal>
-_totalPoints: int

+Menu(): void
+DisplayGoals(): void
+RecordEvent(): void
+GetGoalList(): List<Goal>
+NewGoal(): Goal
+AddGoalToList(Goal): void
+GetTotalPoints(): int
+SetTotalPoints(int points): void
+Save(): void
+Load(): void
}

+abstract Goal
{
-_points: int
-_isComplete: bool

+GetIsComplete(): bool
+SetIsComplete(bool isComplete): void
+AddPointsToTotal(): void
+Abstract MarkAsDone(): void
}

+class SimpleGoal
{
+Override MarkAsDone(): void
}

+class EternalGoal
{
+Override MarkAsDone(): void
}

+class ChecklistGoal
{
-_numberUntilComplete: int
-_numberCurrentlyComplete: int
-_bonusPoints: int

+GetNumberCurrentlyComplete(): int
+SetNumberCurrentlyComplete(): void
+Override MarkAsDone(): void
}

@enduml

